repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        args: [ "--profile=black" ]
  - repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: pytest
        name: Unit Tests
        entry: pytest .
        language: system
        always_run: true
        pass_filenames: false
