repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^LICENSE|\.(html|csv|txt|svg|py)$
      - id: pretty-format-json
        args: [ "--autofix", "--no-ensure-ascii", "--no-sort-keys" ]
      - id: requirements-txt-fixer
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.256'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        pass_filenames: false
        types: [ python ]
        args:
          [
            ".",
            "--recursive=y",
            "--ignore-paths=^tests/",
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
