[tool.poetry]
name = "timtools"
version = "0.33.2"
description = ""
authors = ["Tim Mees <tim.mees83@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
pytest = "^6.2.5"
testfixtures = "^6.18.3"
DateTime = "^4.3"
pandas = "^1.3.3"
setuptools = "^58.2.0"
pytz = "^2021.3"
google-api-python-client = "^2.24.0"
validators = "^0.18.2"
configparser = "^5.0.2"
python-telegram-bot = "^13.7"
google-api-core = "^2.1.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^0.4.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
